env:
  - CXX=g++-4.8
language: node_js
services:
  - mysql
node_js:
  - '8'
sudo: false
env:
  - DB_HOST=127.0.0.1
    DB_USERNAME="root"
    DB_PASSWORD=""
    DB_DATABASE="webmaker_test"
    DBOPTIONS_PORT=3306
    DBOPTIONS_DIALECT="mysql"
before_install:
  - mysql -e 'CREATE DATABASE webmaker_test;'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
